### ISSUE TITLE
Requiring postUrl in componentConfig invalidates flux model

### ISSUE THREAD

**Issue by tc** [felixrieseberg/React-Dropzone-Component#7]
Ideally, postUrl shouldn't be required and the user should be able to call their custom upload logic(ie. in the store object of a flux app) in  "drop" event handler.

**Comment by felixrieseberg** [comment]
Solved in [0.3.2](https://github.com/felixrieseberg/React-Dropzone-Component/commit/cf965aaa9775db88a89d4a7c723dfb6d8a94d9b4).

**Comment by tc** [comment]
looks good, thanks!

**Comment by TimDaub** [comment]
Isn't this still a problem?
`DropzoneComponent` still checks if postUrl is defined in componentDidMount: https://github.com/felixrieseberg/React-Dropzone-Component/blob/cf965aaa9775db88a89d4a7c723dfb6d8a94d9b4/lib/dropzone.js

I can't get it to work on version 4.0

**Comment by felixrieseberg** [comment]
Erm, yeah, you're right. Fixing.

**Comment by felixrieseberg** [comment]
Update: It's in 4.1. It's no longer breaking, but instead just giving a gentle `console.info` nudge if you have neither a `postUrl` nor a `drop` event handler.

**Comment by TimDaub** [comment]
Awesome, are you going to push that in the next couples of minutes already?

Really cool that you're taking actions so quickly :+1: :)

**Comment by TimDaub** [comment]
I proposed a solution to the missing configuration part and documented it. What do you think @felixrieseberg
